apiVersion: apps/v1
kind: Deployment
metadata:
  name: gab-app-deployment
  labels:
    app: gab-app
    environment: "dev"  # Set a default value or remove this line if you want to set it in the pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gab-app
  template:
    metadata:
      labels:
        app: gab-app
        environment: "dev"  # Same as above
    spec:
      containers:
        - name: gab-app-container
          image: "${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPOSITORY}:latest"  # Use placeholders here
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "dev"  # You can replace this with a pipeline variable
      imagePullSecrets:
        - name: gab-app-secret
