apiVersion: apps/v1
kind: Deployment
metadata:
  name: gab-app-deployment
  labels:
    app: gab-app
    environment: "${ENVIRONMENT}"  # Environment variable will be injected 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gab-app
  template:
    metadata:
      labels:
        app: gab-app
        environment: "${ENVIRONMENT}"  # Environment variable will be injected
    spec:
      containers:
        - name: gab-app-container
          image: "{{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.{{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}"
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "${ENVIRONMENT_LABEL}"  # Set from the pipeline
---
