# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gab-app-service
  labels:
    app: gab-app
    environment: ""
spec:
  type: LoadBalancer  # Exposes the service via an external load balancer (for public access)
  selector:
    app: gab-app
  ports:
    - protocol: TCP
      port: 80         # External port for the service
      targetPort: 80   # The port where the container is running
      nodePort: 3000
